# Database
DB_NAME = None
DB_LOCATION = None
DB_USER = None
DB_PASSWORD = None

#Aviationstack API
AVIATIONSTACK_HOST = None
ACCESS_KEY = None


#ChatBot
CHATBOT_HOST = None


MESSAGE_TYPE_BUTTONS = 'buttons'
MESSAGE_TYPE_TEXT = 'text'
MESSAGE_TYPE_SEARCH = 'search'
MESSAGE_TYPE_BOOKING = 'booking'
MESSAGE_TYPE_CHECKBOOKING = 'checkbooking'
MESSAGE_TYPE_FEEDBACK = 'feedback'
MESSAGE_TYPE_HELP_REQUEST = 'help'
MESSAGE_TYPE_HELP_REQUEST_ACCEPTED = 'help_accepted'
MESSAGE_TYPE_HELP_REQUEST_FINISHED = 'help_finished'


NORMAL_STATUS = 0
HELP_REQUEST_STATUS = 1
HELP_ON_PROGRESS_STATUS = 2
REAl_AGENT_STATUS = 4